import fs from"node:fs/promises";
import{createRequire}from"node:module";
const require=createRequire(import.meta.url),XLSX=require("../dist/assets/xlsx.full.min.js");
const input=process.argv[2]||"Data/справочникSEB.xlsx",reportPath=process.argv[3]||".artifacts/photo-refresh-report.json",apply=process.argv.includes("--apply"),outputArg=process.argv.find(x=>x.startsWith("--output=")),output=outputArg?.slice(9)||input;
const source=await fs.readFile(input),workbook=XLSX.read(source,{type:"buffer",cellFormula:true,cellStyles:true}),sheet=workbook.Sheets[workbook.SheetNames[0]],grid=XLSX.utils.sheet_to_json(sheet,{header:1,defval:null,raw:true}),headers=new Map(grid[0].map((value,index)=>[String(value??"").trim(),index])),articleIndex=headers.get("Артикул"),photoIndex=headers.get("Sulpak.photoUrl");
if(articleIndex===undefined||photoIndex===undefined)throw Error("Catalog columns are missing");
const normalize=value=>String(value??"").trim().replace(/\.0$/,"");
const items=grid.slice(1).map((row,index)=>({row:index+2,article:normalize(row[articleIndex]),current:String(row[photoIndex]??"").trim()})).filter(item=>item.article);
const results=new Array(items.length);let cursor=0;
async function worker(){while(true){const index=cursor++;if(index>=items.length)return;const item=items[index],url=`https://sulpak-api.evinent.site/api/search/autocomplete/1/3/${encodeURIComponent(item.article)}/true/`;let result={...item,status:"error"};for(let attempt=1;attempt<=3;attempt++){try{const response=await fetch(url,{headers:{Accept:"application/json",Referer:"https://www.sulpak.kz/","User-Agent":"SebBN photo verifier/1.0"},signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error(`HTTP ${response.status}`);const payload=await response.json(),products=payload?.products||[],product=products.find(value=>normalize(value?.code)===item.article);if(!product){result={...item,status:"not_found"};break}const latest=String(product.photoUrl??"").trim();result={...item,status:latest?latest===item.current?"current":"changed":"no_photo",latest,title:String(product.title??"")};break}catch(error){result={...item,status:"error",error:String(error?.message||error)};if(attempt<3)await new Promise(resolve=>setTimeout(resolve,attempt*500))}}results[index]=result}}
await Promise.all(Array.from({length:6},worker));
const changed=results.filter(item=>item.status==="changed"),report={checked:results.length,current:results.filter(item=>item.status==="current").length,changed:changed.length,notFound:results.filter(item=>item.status==="not_found").length,noPhoto:results.filter(item=>item.status==="no_photo").length,errors:results.filter(item=>item.status==="error").length,changes:changed,issues:results.filter(item=>!["current","changed"].includes(item.status))};
if(apply){for(const item of changed){const cell=XLSX.utils.encode_cell({r:item.row-1,c:photoIndex});sheet[cell]={...(sheet[cell]||{}),t:"s",v:item.latest,w:item.latest}}const bytes=XLSX.write(workbook,{type:"buffer",bookType:"xlsx",cellStyles:true});await fs.writeFile(output,bytes)}
await fs.mkdir(new URL("../.artifacts/",import.meta.url),{recursive:true});await fs.writeFile(reportPath,JSON.stringify(report,null,2));console.log(JSON.stringify({...report,changes:undefined,issues:undefined}));
